Tenth lesson
Pavlooid/Test-Guru pull request #10
Opened 2023-09-22 12:13 UTC by Pavlooid

without last task

2023-09-22 14:15 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +  def start
экшен `start` в контроллере админа не нужен
это функционал пользователя

2023-09-22 14:15 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[start]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2023-09-24 10:31 UTC, VidgarVii requested changes

2023-09-24 10:31 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    flash[:notice] =  "Привет, #{current_user.first_name}!" unless current_user.is_a?(Admin)
этот метод должен просто возвращать путь
то что он еще и флеш устанавливает - неожиданный сайд эффект
к примеру, есть задача:
в админке выводить список пользователей с урлами, куда каждый будет редиректнут после логина
метод называется `after_sign_in_path_for(user)` - вполне логично им воспользоваться
и вдруг неожиданность - у админа почему-то выводится флеш-привествие )))
ТЗ: "... после входа, выводить флэш-сообщение ..."
обрати внимание - "после входа", т.е. установку флеша надо делать там, где происходит логин пользователя (создание сессии), т.е. в `SessionsController`

2023-09-24 11:38 UTC, Pavlooid commented on app/controllers/application_controller.rb
> +    flash[:notice] =  "Привет, #{current_user.first_name}!" unless current_user.is_a?(Admin)
Да, выглядит глупо

2023-09-25 11:37 UTC, merged