Thirteen_lesson
Pavlooid/Test-Guru pull request #13
Opened 2023-10-02 12:08 UTC by Pavlooid

2023-10-05 14:46 UTC, VidgarVii requested changes

2023-10-05 14:46 UTC, VidgarVii commented on Gemfile
> +gem 'faraday'
он ведь больше не используется. Лучше удалить

2023-10-05 14:46 UTC, VidgarVii commented on Gemfile
> +gem 'dotenv-rails', groups: [:development, :test]
пару строк ниже такая группа уже объявлена. Устанавливай гем лучше там

2023-10-05 14:46 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  before_action :find_test_passage, only: %i[gist show result update]
Повод вспомнить про REST.
Gist это ресурс. Значит согласно rails way и REST для создания ресурса и записи в БД объекта Gist должен быть отдельный контроллер с экшеном create

2023-10-05 14:46 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    flash_options = if result.success?
предикатные методы должны возвращать только true/false

2023-10-05 14:46 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  ACCESS_TOKEN = ENV['ACCESS_TOKEN']
Плохое название для токена. В проектах таких токенов мб сотни. Лучше явно прописывать за что отвечает ключ. Предлагаю для примера GITHUB_ACCESS_TOKEN

2023-10-05 14:46 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    Octokit::Client.new(access_token: ACCESS_TOKEN, api_endpoint: ROOT_ENDPOINT)
по документации достаточно передать только access_token

2023-10-05 14:46 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
еще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```
уменьшит потребление памяти и выглядит лучше

2023-10-05 14:59 UTC, Pavlooid commented on app/services/gist_question_service.rb
> +  ACCESS_TOKEN = ENV['ACCESS_TOKEN']
Понял

2023-10-07 13:45 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    flash_options = if result.success?
метод success? является предикатным. И он возвращает либо true либюо false
Записывать его в переменную и дальше передавать в redirect_to нет смысла

2023-10-09 10:34 UTC, merged

2023-10-09 10:35 UTC, Pavlooid commented on app/controllers/gists_controller.rb
> +    flash_options = if result.success?
Понял