ninth lesson
Pavlooid/Test-Guru pull request #9
Opened 2023-09-14 13:25 UTC by Pavlooid

2023-09-16 12:58 UTC, VidgarVii requested changes

2023-09-16 12:58 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:return] = request.path
данная запись нужна только для не залогиненного юзера

2023-09-16 12:58 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    redirect_to login_path, alert: 'Для продолжения требуется войти в систему!' unless current_user
принятно по возможности использовать if, а не unless. Так как проще воспринимается

2023-09-16 12:58 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:return] = request.path
return очень слабое название для ключа. Можно быстро забыть и не понять, зачем нужна эта кука

2023-09-16 12:58 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:return]
а если нет такой записи? То будет ошибка
Если записи нет. То надо редиректить юзера на дефолтную страницу

2023-09-16 12:58 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:return]
и кстати можно сразу удалить return, так как больше она будет не нужна

2023-09-16 12:58 UTC, VidgarVii commented on app/helpers/flash_helper.rb
> +  def flash_message(_alert)
здесь более правильно было бы принимать в аргументах `type`
потому что флеш-сообщения могут быть разных типов, а этот хелпер вернет сообщение, только если это `:alert`

2023-09-16 12:58 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>    end
не исправлено создание автора теста

2023-09-16 12:58 UTC, VidgarVii commented on config/routes.rb
> +  get :logout, to: 'sessions#destroy'
Это лучше сделать HTTP-методом DELETE, чтоб соблюдалась семантика REST. Ресурсы удаляют только методом DELETE

2023-09-17 11:24 UTC, Pavlooid commented on app/helpers/flash_helper.rb
> +  def flash_message(_alert)
Принял

2023-09-17 11:58 UTC, Pavlooid commented on app/controllers/tests_controller.rb
>    end
Не понял о чём конкретно речь

2023-09-17 14:43 UTC, VidgarVii requested changes

2023-09-17 14:43 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      cookies.delete :redirect_to_request_path
удалять можно сразу при редиректе. Смотри что возвращает метод delete

2023-09-17 14:43 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>    end
у нас теперь есть залогиненные пользователи системы. Можно считать, что пользователь, который создал тест и будет являться его автором

2023-09-18 07:10 UTC, VidgarVii requested changes

2023-09-18 07:10 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:redirect_to_request_path] || root_path, method: :delete
1 https://github.com/Pavlooid/Test-Guru/pull/9#discussion_r1327957997 не сделано
2 method: :delete что тут происходит?

2023-09-18 07:10 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>    end
не исправлено

2023-09-18 10:05 UTC, Pavlooid commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:redirect_to_request_path] || root_path, method: :delete
Судя по кукам method: :delete, перенаправлял и удалял всё как надо, но переделал.

2023-09-18 10:10 UTC, Pavlooid commented on app/controllers/tests_controller.rb
>    end
Всё, понял в чем дело, исправляю

2023-09-18 14:34 UTC, VidgarVii requested changes

2023-09-18 14:34 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>      if @test.save
если будет ошибка в валидации, то до этой строчки кода дело не дойдёт

2023-09-19 05:50 UTC, VidgarVii requested changes

2023-09-19 05:50 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>      if @test.save
не верно исправлено 
https://github.com/Pavlooid/Test-Guru/pull/9/files#r1328826159
Происходит двойная попытка записать тест в базу

2023-09-19 14:23 UTC, merged